{% set name = "deco" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deco-{{ version }}.tar.gz
  sha256: ced26347fead556b379e28fd2593b66c612544cb5f3bf42aef81d816c539d960

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - deco
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alex-sherman/deco
  summary: A decorator for concurrency
  description: |
    A simplified parallel computing model for Python. 
    DECO automatically parallelizes Python programs, 
    and requires minimal modifications to existing serial programs.
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/alex-sherman/deco/wiki
  dev_url: https://github.com/alex-sherman

extra:
  recipe-maintainers:
    - adamamer20
